default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: stamapdb
  username: root
  password: root

test:
  <<: *default
  database: stamapdb
  username: root
  password: root

production:
  <<: *default
  database: stamapdb
  username: root
  password: root
